MonProjetMVC/Models/Ticket.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MonProjetMVC.Models
{
    public class Ticket
    {
        public int ticketId { get; set; }

        public string? subject { get; set; }

        public string? description { get; set; }

        public string? status { get; set; }

        public string? priority { get; set; }
        public DateTime? createdAt { get; set; } = DateTime.UtcNow;
    }
}

MonProjetMVC/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MonProjetMVC.Filter;
using MonProjetMVC.Models;
using MonProjetMVC.Services;
using X.PagedList.Extensions;

namespace MonProjetMVC.Controllers
{
    [SessionValidationFilter]

    public class TicketController : Controller
    {
        private readonly ILogger<TicketController> _logger;
        private readonly ApiService _apiService;

        public TicketController(ILogger<TicketController> logger, ApiService apiService)
        {
            _logger = logger;
            _apiService = apiService;
        }
        public async Task<IActionResult> GetTicket()
        {
            // string? jsessionId = HttpContext.Session.GetString("JSessionId");
            // var jsonResponse = await _apiService.TestOAuthApiWithSessionIdAsync(jsessionId, "/api/dashboard/tickets");
            var jsonResponse = await _apiService.TestOAuthApiWithSessionIdAsync2("/api/dashboard/tickets");
            Console.WriteLine(jsonResponse);
            List<Depense>? budgets = JsonSerializer.Deserialize<List<Depense>>(jsonResponse, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

            return View("Tickets", budgets);

        }
        public async Task<IActionResult> GetTicketTous(int? page)
        {
            int pageSize = 5;
            int pageNumber = page ?? 1;
            // string? jsessionId = HttpContext.Session.GetString("JSessionId");
            // var jsonResponse = await _apiService.TestOAuthApiWithSessionIdAsync(jsessionId, "/api/dashboard/tickets");
            var jsonResponse = await _apiService.TestOAuthApiWithSessionIdAsync2("/api/dashboard/ticketsTous");
            // Console.WriteLine(jsonResponse);
            List<Depense>? budgets = JsonSerializer.Deserialize<List<Depense>>(jsonResponse, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
            var depenses = budgets
            .OrderByDescending(d => d.ticket.createdAt) // Tri par date de création
            .ToPagedList(pageNumber, pageSize);
            return View("TicketsTous", depenses);

        }
        public async Task<IActionResult> Suprimmer(string nom)
        {
            // string? jsessionId = HttpContext.Session.GetString("JSessionId");
            ReponseJSON reponseJSON = new ReponseJSON
            {
                nom = "id",
                valeur = Convert.ToDouble(nom)
            };
            // var response = await _apiService.EnvoyerBudgetAsync(reponseJSON, jsessionId, "http://localhost:8080/api/dashboard/deleteTicket");
            var response = await _apiService.EnvoyerBudgetAsync2(reponseJSON, "http://localhost:8080/api/dashboard/deleteTicket");

            Console.WriteLine("Réponse de l'API: " + response);
            return RedirectToAction("GetTicket");
        }
        public async Task<IActionResult> SuprimmerTous(string nom)
        {
            // string? jsessionId = HttpContext.Session.GetString("JSessionId");
            ReponseJSON reponseJSON = new ReponseJSON
            {
                nom = "id",
                valeur = Convert.ToDouble(nom)
            };
            // var response = await _apiService.EnvoyerBudgetAsync(reponseJSON, jsessionId, "http://localhost:8080/api/dashboard/deleteTicket");
            var response = await _apiService.EnvoyerBudgetAsync2(reponseJSON, "http://localhost:8080/api/dashboard/deleteTicket");


            return RedirectToAction("GetTicket");
        }
        [HttpPost]
        public async Task<IActionResult> ModificationTicket(double nom, string id)
        {
            // string? jsessionId = HttpContext.Session.GetString("JSessionId");
            ReponseJSON reponseJSON = new ReponseJSON
            {
                nom = id,
                valeur = nom
            };
            // var response = await _apiService.EnvoyerBudgetAsync(reponseJSON, jsessionId, "http://localhost:8080/api/dashboard/modificationTicket");
            var response = await _apiService.EnvoyerBudgetAsync2(reponseJSON, "http://localhost:8080/api/dashboard/modificationTicket");

            Console.WriteLine("Réponse de l'API: " + response);
            return RedirectToAction("GetTicket");
        }
        public async Task<IActionResult> Modifier(string nom)
        {
            // string? jsessionId = HttpContext.Session.GetString("JSessionId");
            ReponseJSON reponseJSON = new ReponseJSON
            {
                nom = "id",
                valeur = Convert.ToDouble(nom)
            };
            // var response = await _apiService.EnvoyerBudgetAsync(reponseJSON, jsessionId, "http://localhost:8080/api/dashboard/getModificationTicket");
            var response = await _apiService.EnvoyerBudgetAsync2(reponseJSON, "http://localhost:8080/api/dashboard/getModificationTicket");

            Console.WriteLine("Réponse de l'API: " + response);
            return View("Modification", JsonSerializer.Deserialize<Depense>(response, new JsonSerializerOptions { PropertyNameCaseInsensitive = true }));
        }
        [HttpPost]
        public async Task<IActionResult> ModificationTicketTous(double nom, string id)
        {
            // string? jsessionId = HttpContext.Session.GetString("JSessionId");
            ReponseJSON reponseJSON = new ReponseJSON
            {
                nom = id,
                valeur = nom
            };
            // var response = await _apiService.EnvoyerBudgetAsync(reponseJSON, jsessionId, "http://localhost:8080/api/dashboard/modificationTicket");
            var response = await _apiService.EnvoyerBudgetAsync2(reponseJSON, "http://localhost:8080/api/dashboard/modificationTicket");

            Console.WriteLine("Réponse de l'API: " + response);
            return RedirectToAction("GetTicketTous");
        }
        public async Task<IActionResult> ModifierTous(string nom)
        {
            // string? jsessionId = HttpContext.Session.GetString("JSessionId");
            ReponseJSON reponseJSON = new ReponseJSON
            {
                nom = "id",
                valeur = Convert.ToDouble(nom)
            };
            // var response = await _apiService.EnvoyerBudgetAsync(reponseJSON, jsessionId, "http://localhost:8080/api/dashboard/getModificationTicket");
            var response = await _apiService.EnvoyerBudgetAsync2(reponseJSON, "http://localhost:8080/api/dashboard/getModificationTicket");

            Console.WriteLine("Réponse de l'API: " + response);
            return View("ModificationTous", JsonSerializer.Deserialize<Depense>(response, new JsonSerializerOptions { PropertyNameCaseInsensitive = true }));
        }
        [HttpPost]
        public async Task<IActionResult> RechercheMultiCritere(DateTime dateDebut, DateTime dateFin, double valeur)
        {
            List<ReponseJSON> reponseJSONs = new List<ReponseJSON>();
            Console.WriteLine(int.MinValue);
            if (dateFin == DateTime.MinValue)
            {
                dateFin = DateTime.MaxValue;
            }
            ReponseJSON reponseJSON1 = new ReponseJSON
            {
                nom = dateDebut.ToString(),
                valeur = 0.0
            };
            ReponseJSON reponseJSON2 = new ReponseJSON
            {
                nom = dateFin.ToString(),
                valeur = 0.0
            };
            reponseJSONs.Add(reponseJSON1);
            reponseJSONs.Add(reponseJSON2);
            // var response = await _apiService.EnvoyerBudgetAsync(reponseJSON, jsessionId, "http://localhost:8080/api/dashboard/deleteTicket");
            var response = await _apiService.EnvoyerBudgetAsync2(reponseJSONs, "http://localhost:8080/api/dashboard/multicritereDepenseTicket");
            List<Depense>? budgets = JsonSerializer.Deserialize<List<Depense>>(response, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

            return View("MultiCritere", budgets);
        }
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

MonProjetMVC/Views/Ticket/Modification.cshtml
@model MonProjetMVC.Models.Depense


<div>
    <h2>Modification: @Model.ticket.subject</h2>

    <form class="form" method="post" asp-action="ModificationTicket" asp-controller="Ticket">
        <label for="nom">Nouveau valeur :</label>
        <input type="number" id="nom" name="nom" required value="@((double)Model.valeurDepense)" />
        <input type="hidden" value="@Model.depenseId" name="id">
        <button type="submit">Soumettre</button>
    </form>
</div>

MonProjetMVC/Views/Ticket/ModificationTous.cshtml
@model MonProjetMVC.Models.Depense


<div>
    <h2>Modification: @Model.ticket.subject</h2>

    <form class="form" method="post" asp-action="ModificationTicketTous" asp-controller="Ticket">
        <label for="nom">Nouveau valeur :</label>
        <input type="number" id="nom" name="nom" required value="@((double)Model.valeurDepense)" />
        <input type="hidden" value="@Model.depenseId" name="id">
        <button type="submit">Soumettre</button>
    </form>
</div>

MonProjetMVC/Views/Ticket/MultiCritere.cshtml
@model List<MonProjetMVC.Models.Depense>
<div>
    <h2>Liste des Tickets</h2>
    <form class="form" method="post" asp-action="RechercheMultiCritere" asp-controller="Ticket">
        <label for="nom">Date debut :</label>
        <input type="datetime-local" name="dateDebut">
        <label for="nom">Date fin :</label>
        <input type="datetime-local" name="dateFin">
        <input type="submit" value="Soumetre">
    </form>
    <table class="table">
        <tr>
            <th>ID</th>
            <th>Subject</th>
            <th>Status</th>
            <th>Description</th>
            <th>Somme</th>
            <th>Created at</th>
            <th>Etat</th>
            <th>Modifier</th>
            <th>Supprimer</th>
        </tr>
        @foreach (var depense in Model)
        {
            <tr>
                <td>@depense.ticket.ticketId</td>
                <td>@depense.ticket.subject</td>
                <td>@depense.ticket.status</td>
                <td>@depense.ticket.description</td>
                <td>@depense.valeurDepense</td>
                <td>@depense.ticket.createdAt</td>
                @if (depense.etat == 1)
                {
                    <td>Valider</td>
                }
                @if (depense.etat == 0)
                {
                    <td>en attente...</td>
                }
                @if (depense.etat == -1)
                {
                    <td>refuser</td>
                }

                <td><a href="@Url.Action("Modifier", "Ticket", new { nom = depense.ticket.ticketId })">Modifier</a></td>
                <td><a href="@Url.Action("Suprimmer", "Ticket", new { nom = depense.ticket.ticketId })">Supprimer</a></td>
            </tr>
        }
    </table>
</div>

MonProjetMVC/Views/Ticket/Tickets.cshtml
@model List<MonProjetMVC.Models.Depense>
<div>
    <h2>Liste des Tickets</h2>
    <table class="table">
        <tr>
            <th>ID</th>
            <th>Subject</th>
            <th>Status</th>
            <th>Description</th>
            <th>Somme</th>
            <th>Created at</th>
            <th>Etat</th>
            <th>Modifier</th>
            <th>Supprimer</th>
        </tr>
        @foreach (var depense in Model)
        {
            <tr>
                <td>@depense.ticket.ticketId</td>
                <td>@depense.ticket.subject</td>
                <td>@depense.ticket.status</td>
                <td>@depense.ticket.description</td>
                <td>@depense.valeurDepense</td>
                <td>@depense.ticket.createdAt</td>
                @if (depense.etat == 1)
                {
                    <td>Valider</td>
                }
                @if (depense.etat == 0)
                {
                    <td>en attente...</td>
                }
                @if (depense.etat == -1)
                {
                    <td>refuser</td>
                }

                <td><a href="@Url.Action("Modifier", "Ticket", new { nom = depense.ticket.ticketId })">Modifier</a></td>
                <td><a href="@Url.Action("Suprimmer", "Ticket", new { nom = depense.ticket.ticketId })">Supprimer</a></td>
            </tr>
        }
    </table>
</div>

MonProjetMVC/Views/Ticket/TicketsTous.cshtml
@using X.PagedList.Mvc.Core
@using X.PagedList
@model IPagedList<MonProjetMVC.Models.Depense>
<style>
    .pagination {
        text-align: center;
        margin-top: 20px;
    }

    .pagination a,
    .pagination span {
        padding: 8px 12px;
        margin: 2px;
        text-decoration: none;
        background-color: #007bff;
        color: white;
        border-radius: 4px;
    }

    .pagination .active {
        background-color: #0056b3;
        font-weight: bold;
    }
</style>
<div>
    <h2>Liste des Tickets</h2>
    <form class="form" method="post" asp-action="RechercheMultiCritere" asp-controller="Ticket">
        <label for="nom">Date debut :</label>
        <input type="datetime-local" name="dateDebut">
        <label for="nom">Date fin :</label>
        <input type="datetime-local" name="dateFin">
        <button type="submit">Rechercher</button>
    </form>
    <table class="table">
        <tr>
            <th>ID</th>
            <th>Subject</th>
            <th>Status</th>
            <th>Description</th>
            <th>Somme</th>
            <th>Created at</th>
            <th>Etat</th>
            <th>Modifier</th>
            <th>Supprimer</th>
        </tr>
        @foreach (var depense in Model)
        {
            <tr>
                <td>@depense.ticket.ticketId</td>
                <td>@depense.ticket.subject</td>
                <td>@depense.ticket.status</td>
                <td>@depense.ticket.description</td>
                <td>@depense.valeurDepense</td>
                <td>@depense.ticket.createdAt</td>
                @if (depense.etat == 1)
                {
                    <td>Valider</td>
                }
                else if (depense.etat == 0)
                {
                    <td>en attente...</td>
                }
                else
                {
                    <td>refuser</td>
                }
                <td><a href="@Url.Action("ModifierTous", "Ticket", new { nom = depense.ticket.ticketId })">Modifier</a></td>
                <td><a href="@Url.Action("SuprimmerTous", "Ticket", new { nom = depense.ticket.ticketId })">Supprimer</a>
                </td>
            </tr>
        }
    </table>
    <div class="pagination">
        @Html.PagedListPager(Model, page => Url.Action("GetTicketTous", "Ticket", new { page }))
    </div>
</div>