MonProjetMVC/Models/Lead.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MonProjetMVC.Models
{
    public class Lead
    {
        public int leadId { get; set; }
        public string? name { get; set; }
        public string? status { get; set; }
        public string? phone { get; set; }
        public string? meetingId { get; set; }
        public bool? googleDrive { get; set; }
        public string? googleDriveFolderId { get; set; }
        public DateTime? createdAt { get; set; } = DateTime.UtcNow;
    }
}

MonProjetMVC/Controllers/LeadController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MonProjetMVC.Filter;
using MonProjetMVC.Models;
using MonProjetMVC.Services;

namespace MonProjetMVC.Controllers
{
    [SessionValidationFilter]
    public class LeadController : Controller
    {
        private readonly ILogger<LeadController> _logger;
        private readonly ApiService _apiService;

        public LeadController(ILogger<LeadController> logger, ApiService apiService)
        {
            _logger = logger;
            _apiService = apiService;
        }
        [SessionValidationFilter]
        public async Task<IActionResult> GetLead()
        {
            // string? jsessionId = HttpContext.Session.GetString("JSessionId");
            // var jsonResponse = await _apiService.TestOAuthApiWithSessionIdAsync(jsessionId, "/api/dashboard/leads");
            var jsonResponse = await _apiService.TestOAuthApiWithSessionIdAsync2("/api/dashboard/leads");
            List<Depense>? budgets = JsonSerializer.Deserialize<List<Depense>>(jsonResponse, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

            return View("Leads", budgets);

        }
        public async Task<IActionResult> GetLeadTous()
        {
            // string? jsessionId = HttpContext.Session.GetString("JSessionId");
            // var jsonResponse = await _apiService.TestOAuthApiWithSessionIdAsync(jsessionId, "/api/dashboard/leads");
            var jsonResponse = await _apiService.TestOAuthApiWithSessionIdAsync2("/api/dashboard/leadsTous");
            List<Depense>? budgets = JsonSerializer.Deserialize<List<Depense>>(jsonResponse, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

            return View("LeadsTous", budgets);

        }
        public async Task<IActionResult> Suprimmer(string nom)
        {
            // string? jsessionId = HttpContext.Session.GetString("JSessionId");
            ReponseJSON reponseJSON = new ReponseJSON
            {
                nom = "id",
                valeur = Convert.ToDouble(nom)
            };
            // var response = await _apiService.EnvoyerBudgetAsync(reponseJSON, jsessionId, "http://localhost:8080/api/dashboard/deleteLead");
            var response = await _apiService.EnvoyerBudgetAsync2(reponseJSON, "http://localhost:8080/api/dashboard/deleteLead");

            Console.WriteLine("Réponse de l'API: " + response);
            return RedirectToAction("GetLead");
        }
        public async Task<IActionResult> SuprimmerTous(string nom)
        {
            // string? jsessionId = HttpContext.Session.GetString("JSessionId");
            ReponseJSON reponseJSON = new ReponseJSON
            {
                nom = "id",
                valeur = Convert.ToDouble(nom)
            };
            // var response = await _apiService.EnvoyerBudgetAsync(reponseJSON, jsessionId, "http://localhost:8080/api/dashboard/deleteLead");
            var response = await _apiService.EnvoyerBudgetAsync2(reponseJSON, "http://localhost:8080/api/dashboard/deleteLead");

            Console.WriteLine("Réponse de l'API: " + response);
            return RedirectToAction("GetLeadTous");
        }
        [HttpPost]
        public async Task<IActionResult> ModificationLead(double nom, string id)
        {
            // string? jsessionId = HttpContext.Session.GetString("JSessionId");
            ReponseJSON reponseJSON = new ReponseJSON
            {
                nom = id,
                valeur = nom
            };
            // var response = await _apiService.EnvoyerBudgetAsync(reponseJSON, jsessionId, "http://localhost:8080/api/dashboard/modificationLead");
            var response = await _apiService.EnvoyerBudgetAsync2(reponseJSON, "http://localhost:8080/api/dashboard/modificationLead");

            Console.WriteLine("Réponse de l'API: " + response);
            return RedirectToAction("GetLead");
        }
        public async Task<IActionResult> Modifier(string nom)
        {
            // string? jsessionId = HttpContext.Session.GetString("JSessionId");
            ReponseJSON reponseJSON = new ReponseJSON
            {
                nom = "id",
                valeur = Convert.ToDouble(nom)
            };
            // var response = await _apiService.EnvoyerBudgetAsync(reponseJSON, jsessionId, "http://localhost:8080/api/dashboard/getModificationLead");
            var response = await _apiService.EnvoyerBudgetAsync2(reponseJSON, "http://localhost:8080/api/dashboard/getModificationLead");

            Console.WriteLine("Réponse de l'API: " + response);
            return View("Modification", JsonSerializer.Deserialize<Depense>(response, new JsonSerializerOptions { PropertyNameCaseInsensitive = true }));
        }
        [HttpPost]
        public async Task<IActionResult> ModificationLeadTous(double nom, string id)
        {
            // string? jsessionId = HttpContext.Session.GetString("JSessionId");
            ReponseJSON reponseJSON = new ReponseJSON
            {
                nom = id,
                valeur = nom
            };
            // var response = await _apiService.EnvoyerBudgetAsync(reponseJSON, jsessionId, "http://localhost:8080/api/dashboard/modificationLead");
            var response = await _apiService.EnvoyerBudgetAsync2(reponseJSON, "http://localhost:8080/api/dashboard/modificationLead");

            Console.WriteLine("Réponse de l'API: " + response);
            return RedirectToAction("GetLeadTous");
        }
        public async Task<IActionResult> ModifierTous(string nom)
        {
            // string? jsessionId = HttpContext.Session.GetString("JSessionId");
            ReponseJSON reponseJSON = new ReponseJSON
            {
                nom = "id",
                valeur = Convert.ToDouble(nom)
            };
            // var response = await _apiService.EnvoyerBudgetAsync(reponseJSON, jsessionId, "http://localhost:8080/api/dashboard/getModificationLead");
            var response = await _apiService.EnvoyerBudgetAsync2(reponseJSON, "http://localhost:8080/api/dashboard/getModificationLead");

            Console.WriteLine("Réponse de l'API: " + response);
            return View("ModificationTous", JsonSerializer.Deserialize<Depense>(response, new JsonSerializerOptions { PropertyNameCaseInsensitive = true }));
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

MonProjetMVC/Views/Lead/Leads.cshtml
@model List<MonProjetMVC.Models.Depense>
<div>
    <h2>Liste des Leads</h2>
    <table class="table">
        <tr>
            <th>ID</th>
            <th>Nom</th>
            <th>Status</th>
            <th>Created at</th>
            <th>Somme</th>
            <th>Etat</th>
            <th>Modifier</th>
            <th>Supprimer</th>
        </tr>
        @foreach (var depense in Model)
        {
            <tr>
                <td>@depense.lead.leadId</td>
                <td>@depense.lead.name</td>
                <td>@depense.lead.status</td>
                <td>@depense.lead.createdAt</td>
                <td>@depense.valeurDepense</td>
                @if (depense.etat == 1)
                {
                    <td>Valider</td>
                }
                @if (depense.etat == 0)
                {
                    <td>en attente...</td>
                }
                @if (depense.etat == -1)
                {
                    <td>refuser</td>
                }
                <td><a href="@Url.Action("Modifier", "Lead", new { nom = depense.depenseId })">Modifier</a></td>
                <td><a href="@Url.Action("Suprimmer", "Lead", new { nom = depense.depenseId })">Supprimer</a></td>
            </tr>
        }
    </table>
</div>

MonProjetMVC/Views/Lead/LeadsTous.cshtml
@model List<MonProjetMVC.Models.Depense>
<div>
    <h2>Liste des Leads</h2>
    <table class="table">
        <tr>
            <th>ID</th>
            <th>Nom</th>
            <th>Status</th>
            <th>Created at</th>
            <th>Somme</th>
            <th>Etat</th>
            <th>Modifier</th>
            <th>Supprimer</th>
        </tr>
        @foreach (var depense in Model)
        {
            <tr>
                <td>@depense.lead.leadId</td>
                <td>@depense.lead.name</td>
                <td>@depense.lead.status</td>
                <td>@depense.lead.createdAt</td>
                @if (depense.etat == 1)
                {
                    <td>Valider</td>
                }
                @if (depense.etat == 0)
                {
                    <td>en attente...</td>
                }
                @if (depense.etat == -1)
                {
                    <td>refuser</td>
                }
                <td>@depense.valeurDepense</td>
                <td><a href="@Url.Action("ModifierTous", "Lead", new { nom = depense.depenseId })">Modifier</a></td>
                <td><a href="@Url.Action("SuprimmerTous", "Lead", new { nom = depense.depenseId })">Supprimer</a></td>
            </tr>
        }
    </table>
</div>

MonProjetMVC/Views/Lead/Modification.cshtml
@model MonProjetMVC.Models.Depense

<div>
    <h2>Modification: @Model.lead.name</h2>

    <form class="form" method="post" asp-action="ModificationLead" asp-controller="Lead">
        <label for="nom">Nouveau valeur :</label>
        <input type="number" id="nom" name="nom" required value="@((double)Model.valeurDepense)" />
        <input type="hidden" value="@Model.depenseId" name="id">
        <button type="submit">Soumettre</button>
    </form>
</div>

MonProjetMVC/Views/Lead/ModificationTous.cshtml
@model MonProjetMVC.Models.Depense

<div>
    <h2>Modification: @Model.lead.name</h2>

    <form class="form" method="post" asp-action="ModificationLeadTous" asp-controller="Lead">
        <label for="nom">Nouveau valeur :</label>
        <input type="number" id="nom" name="nom" required value="@((double)Model.valeurDepense)" />
        <input type="hidden" value="@Model.depenseId" name="id">
        <button type="submit">Soumettre</button>
    </form>
</div>